variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:

  - build
  - test

build:
  stage: build
  script:
  - ./gradlew assemble

test:
  stage: test
  script:
  - ./gradlew test

sonar:
  stage: sonarqube
  script:
    - ./gradlew sonar --info
  dependencies:
    - build
    - test